version: '3.8'

services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    container_name: legal_rails_app
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - legal_app_network

networks:
  legal_app_network:
    driver: bridge